### ISSUE TITLE
cd command bugs

### ISSUE THREAD

**Issue by jgalian** [J-J-Minishell/minishell#4]
- cd ~ no funciona
- cd sin parametros da segmentation fault

**Comment by baringo11** [comment]
he estado mirando esta mañana eso, me pongo ahora con ello

**Comment by jgalian** [comment]
Solucionado

**Comment by jgalian** [comment]
Lo vuelvo a abrir porque he visto que ahora funciona con      cd ~      pero no funciona con        cd ~/lo-que-sea

**Comment by jgalian** [comment]
Corregido
