### ISSUE TITLE
Error Valgrind "invalid read" al usar comillas

### ISSUE THREAD

**Issue by jgalian** [J-J-Minishell/minishell#7]
- si escribes ->    echo "hola       nuestro programa devuelve  ->    hola  
   mientras que bash devuelve  el caracter  >  en una nueva linea y se queda esperando hasta que cierras las comillas

- por otro lado, valgrind muestra un error al usar comillas:

  al usar ->     echo "$USER" 
==20973== Invalid read of size 1
==20973==    at 0x10BCC9: ft_substr (ft_substr.c:31)
==20973==    by 0x10A25D: replace_env_var (env_var.c:40)
==20973==    by 0x10A674: check_env_var (env_var.c:83)
==20973==    by 0x10B206: ft_process_line (process_line.c:40)
==20973==    by 0x10AB56: main (minishell.c:35)
==20973==  Address 0x4a5bdd8 is 0 bytes after a block of size 8 alloc'd
==20973==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20973==    by 0x10BC84: ft_substr (ft_substr.c:25)
==20973==    by 0x10B6EC: special_split (special_split.c:89)
==20973==    by 0x10B1F2: ft_process_line (process_line.c:39)
==20973==    by 0x10AB56: main (minishell.c:35)
==20973== 
==20973== ERROR SUMMARY: 5 errors from 1 contexts (suppressed: 0 from 0)

 al usar   ->     echo "hola
==20525== 1 errors in context 1 of 1:
==20525== **Invalid read of size 1**
==20525==    at 0x10993C: cmd_echo (blt_echo.c:43)
==20525==    by 0x10B100: ft_process_tokken (process_line.c:11)
==20525==    by 0x10B21E: ft_process_line (process_line.c:42)
==20525==    by 0x10AB56: main (minishell.c:35)
==20525==  Address 0x4a5bdd6 is 0 bytes after a block of size 6 alloc'd
==20525==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20525==    by 0x10BC84: ft_substr (ft_substr.c:25)
==20525==    by 0x10B6EC: special_split (special_split.c:89)
==20525==    by 0x10B1F2: ft_process_line (process_line.c:39)
==20525==    by 0x10AB56: main (minishell.c:35)
==20525== 
==20525== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

**Comment by baringo11** [comment]
lo de no cerrar las comillas no lo tenemos que gestionar. pdf: **’ and " should work like in bash except for multiline commands**

**Comment by jgalian** [comment]
> lo de no cerrar las comillas no lo tenemos que gestionar. pdf: **’ and " should work like in bash except for multiline commands**

Genial.
Pero lo otro no consigo arreglarlo. Y eso que ya he corregido muchos similares en otras funciones.

**Comment by jgalian** [comment]
Corregido
