### ISSUE TITLE
fallo al sustituir variable cuando va seguida de algun caracter

### ISSUE THREAD

**Issue by jgalian** [J-J-Minishell/minishell#8]
Cuando ejecutas `echo hola $USER.` bash devuelve `hola jorge.` y nuestro programa `hola`

**Comment by jgalian** [comment]
Creo que lo he solucionado quitando estas lineas de la funcion `len_env_var()`:

```
	 (str[i] != '"' && str[i] != '\'' && str[i] != '\0' && str[i] != ' ' && str[i] != '$')
	 	return (0);
```
pero tengo que comprobar que no afecta a otras cosas.

**Comment by baringo11** [comment]
perfecto, las he borrado ya en el nuevo commit y no hay fallos
